---
- name: Pure Storage and VMware Integration
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Pure: Create Volume "
      import_role:
        name: purestorage
        tasks_from: create_volume.yaml
      
    - name: "Pure: Create Host Group and Mount Volume to Host Group"
      import_role:
        name: purestorage
        tasks_from: configure_initiators.yaml
      
    - name: "VMware: Rescan HBA"
      import_role:
        name: vmware
        tasks_from: rescan_hba.yaml"

    - name: "VMware: Mount Datastore"
      import_role:
        name: vmware
        tasks_from: mount_datastore.yaml
    
