---
# roles/vmware/tasks/main.yml

# 1. Mount datastore
- name: Mount Pure Storage volume as VMware datastore
  import_tasks: mount_datastore.yaml

# 2. Rescan the hba
- name: Rescan HBAs on ESXi host
  import_tasks: rescan_hba.yaml
