- name: Rescan HBAs on ESXi host
  community.vmware.vmware_host_scanhba:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    cluster_name: "{{ vmware_cluster_name }}"
    resfresh_storage: true
  tags: rescan_hba

