- name: Create FC initiator group for ESXi
  purestorage.flasharrayo.purefa_host:
    fa_url: "{{ fa_a_url }}"
    api_token: "{{ fa_a_api_token }}"
    name: "esxi_host_group"
    state: present
    iqn: "{{ iscsi_iqns }}"
  tags: configure_initiators

- name: Connect volume to ESXi FC initiator group
  purestorage.flasharray.purefa_hgroup:
    fa_url: "{{ fa_a_url }}"
    api_token: "{{ fa_a_api_token }}"
    name: "esxi_host_group"
    volumes:
      - "{{ volume_name }}"
    state: present
  tags: configure_initiators



