- name: Create FC initiator group for ESXi
  purestorage.flasharray.purefa_hgroup:
    fa_url: "{{ fa_a_url }}"
    api_token: "{{ fa_a_api_token }}"
    name: "esxi_fc_hgroup"
    state: present
    wwns: "{{ fc_wwns }}"
  tags: configure_initiators

- name: Connect volume to ESXi FC initiator group
  purestorage.flasharray.purefa_hgroup:
    fa_url: "{{ fa_a_url }}"
    api_token: "{{ fa_a_api_token }}"
    name: "esxi_fc_hgroup"
    volumes:
      - "{{ volume_name }}"
    state: present
  tags: configure_initiators
