- name: Create new host on FlashArray
  purestorage.flasharray.purefa_host:
    fa_url: "{{ fa_a_url }}"
    api_token: "{{ fa_a_api_token }}"
    name: "{{ new_host_name }}"
    state: present
    # wwns: "{{ fc_wwns }}"   # Uncomment For FC initiators
    iqn: "{{ iscsi_iqns }}" #  for iSCSI initiators

